name: paleopandas
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - cartopy
  - pip
  - python=3.10
  - jupyter
  # testing
  - nbstripout  # for pre-commit notebook cleanout
  - pre-commit
  - pytest
  - setuptools
  - pip:
    - git+https://github.com/LinkedEarth/Pyleoclim_util.git@Development
