name: paleopandas
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.21.2
  - pandas==1.3.3
  - cartopy=0.20.1
  - pip
  - Python = 3.9.6
  - jupyter
  - nbconvert  # for pre-commit notebook cleanout
  - pre-commit
  - pip:
    - setuptools==56.0.0
    - git+https://github.com/LinkedEarth/Pyleoclim_util.git@Development
