name: paleopandas
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - cartopy
  - pip
  - Python
  - jupyter
  - nbconvert  # for pre-commit notebook cleanout
  - pre-commit
  - pip:
    - --extra-index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple
    - pandas==2.0.0.dev0+664.g86f182829d
    - git+https://github.com/LinkedEarth/Pyleoclim_util.git
