name: paleopandas
channels:
  - conda-forge
dependencies:
  - numpy
  - cartopy
  - pip
  - python<3.11  # pinned back by numba coming from pip
  - jupyterlab
  - nbconvert  # for pre-commit notebook cleanout
  - pre-commit
  - pytest
  - setuptools
  - xarray
  - netcdf4
  - pip:
    - --extra-index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple
    - pandas==2.0.0.dev0+877.g4901410697
    - git+https://github.com/LinkedEarth/Pyleoclim_util.git
    - pangaeapy
