name: Linting

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pre-commit
        run: |
          pip install pre-commit jupyter

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
