name: Test

# Trigger on push to main or on PRs
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install conda dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          activate-environment: paleopandas
          environment-file: environment.yml
          auto-activate-base: true

      - name: Conda list
        run: conda list

      - name: Install extras
        run: |
          python -m ipykernel install --user --name paleopandas
          pip install nbmake

      - name: Run selected notebooks
        run: | 
          pytest --nbmake --nbmake-kernel=paleopandas examples/Playing_with_Series_in_Pyleoclim.ipynb examples/Non-nanosecond_Series.ipynb
